version: "2"
linters:
    default: none
    disable:
        - testpackage
    enable:
        - asciicheck
        - bodyclose
        - depguard
        - dogsled
        - dupl
        - err113
        - errcheck
        - exhaustive
        - funlen
        - gochecknoglobals
        - gochecknoinits
        - gocognit
        - goconst
        - gocritic
        - gocyclo
        - godot
        - godox
        - goprintffuncname
        - gosec
        - govet
        - ineffassign
        - lll
        - misspell
        - mnd
        - nakedret
        - nestif
        - noctx
        - nolintlint
        - prealloc
        - revive
        - rowserrcheck
        - staticcheck
        - testpackage
        - unconvert
        - unparam
        - unused
        - whitespace
        - wsl_v5
    settings:
        dupl:
            threshold: 100
        funlen:
            lines: 100
            statements: 50
        goconst:
            min-len: 2
            min-occurrences: 2
        gocritic:
            disabled-checks:
                - dupImport
                - ifElseChain
                - octalLiteral
                - whyNoLint
                - wrapperFunc
            enabled-tags:
                - diagnostic
                - experimental
                - opinionated
                - performance
                - style
        gocyclo:
            min-complexity: 15
        govet:
            settings:
                printf:
                    funcs:
                        - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
                        - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
                        - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
                        - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
        lll:
            line-length: 150
        misspell:
            locale: US
        nolintlint:
            require-explanation: false
            require-specific: false
            allow-unused: false
    exclusions:
        generated: lax
        presets:
            - comments
            - common-false-positives
            - legacy
            - std-error-handling
        rules:
            - linters:
                  - mnd
              path: _test\.go
        paths:
            - third_party$
            - builtin$
            - examples$
formatters:
    enable:
        - gofmt
        - goimports
    settings:
        goimports:
            local-prefixes:
                - github.com/golangci/golangci-lint
    exclusions:
        generated: lax
        paths:
            - third_party$
            - builtin$
            - examples$
