project_name: containerlab
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/srl-wim/container-lab/cmd.version={{.Version}} -X github.com/srl-wim/container-lab/cmd.commit={{.ShortCommit}} -X github.com/srl-wim/container-lab/cmd.date={{.Date}}
    goos:
      - linux
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

nfpms:
  - id: "containerlab"
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    package_name: "containerlab"
    maintainer: "Wim Henderickx <wim.henderickx@nokia.com>"
    description: |
      containerlab written in go
    vendor: "Nokia"
    license: "BSD 2"
    formats:
      - rpm
      - deb
    bindir: /usr/local/bin
    config_files:
      ./lab-examples/wan-topo.yml: "/etc/containerlab/lab-examples/wan-topo.yml"
      ./lab-examples/simple.yml: "/etc/containerlab/lab-examples/simple.yml"
      ./lab-examples/arista-topo.yml: "/etc/containerlab/lab-examples/arista-topo.yml"
      ./lab-examples/external-bridge.yml: "/etc/containerlab/lab-examples/external-bridge.yml"
      ./templates/ca/csr-root-ca.json: "/etc/containerlab/templates/ca/csr-root-ca.json"
      ./templates/ca/csr.json: "/etc/containerlab/templates/ca/csr.json"
      ./templates/srl/srlconfig.tpl: "/etc/containerlab/templates/srl/srlconfig.tpl"
      ./templates/srl/srl_env.conf: "/etc/containerlab/templates/srl/srl_env.conf"
      ./templates/srl/topology-7220IXRD1.yml: "/etc/containerlab/templates/srl/topology-7220IXRD1.yml"
      ./templates/srl/topology-7220IXRD2.yml: "/etc/containerlab/templates/srl/topology-7220IXRD2.yml"
      ./templates/srl/topology-7220IXRD3.yml: "/etc/containerlab/templates/srl/topology-7220IXRD3.yml"
      ./templates/srl/topology-7250IXR6.yml: "/etc/containerlab/templates/srl/topology-7250IXR6.yml"
      ./templates/srl/topology-7250IXR10.yml: "/etc/containerlab/templates/srl/topology-7250IXR10.yml"
    overrides:
      rpm:
        scripts:
