repos:
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.3
    hooks:
      - id: codespell
        args:
          # Networking terms are intentional.
          - --ignore-words-list=clos,nd,wan
  - repo: https://github.com/syntaqx/git-hooks
    rev: v0.0.17
    hooks:
      - id: forbid-binary
      - id: go-fmt
      - id: go-test
      - id: go-mod-tidy
      - id: shfmt
