[project]
name = "containerlab"
version = "0.1.0"
description = "Containerlab testing framework"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "robotframework==6.1.1",
    "robotframework-sshlibrary==3.8.0",
]
