package nvidia_cumulusvx

import (
	"context"
	"fmt"
	"maps"
	"path/filepath"
	"slices"
	"strconv"
	"strings"

	clabnodes "github.com/srl-labs/containerlab/nodes"
	clabtypes "github.com/srl-labs/containerlab/types"
	clabutils "github.com/srl-labs/containerlab/utils"
)

const (
	portsConfigName     = "ports.conf"
	portsConfigHeader   = "# Generated by containerlab from extras.cumulus-vx.\n"
	portLayoutDiffField = "Extras.CumulusVX"
	// vrnetlab's tc-tap-ifup script extracts at most three digits from tap names.
	maxInterfaceIndex = 999
)

type portLayout struct {
	ports     int
	breakouts map[int]int
	starts    map[int]int
	lastIndex int
}

func cumulusExtras(cfg *clabtypes.NodeConfig) *clabtypes.CumulusVXExtras {
	if cfg == nil || cfg.Extras == nil {
		return nil
	}
	return cfg.Extras.CumulusVX
}

func newPortLayout(cfg *clabtypes.CumulusVXExtras) (*portLayout, error) {
	if cfg == nil {
		return nil, nil
	}
	if cfg.Ports < 1 || cfg.Ports > maxInterfaceIndex {
		return nil, fmt.Errorf(
			"extras.cumulus-vx.ports must be between 1 and %d",
			maxInterfaceIndex,
		)
	}
	// The launcher extends its default NIC limit using the final breakout slot.
	// A ports-only file would not provision the declared base range by itself.
	if len(cfg.Breakouts) == 0 {
		return nil, fmt.Errorf("extras.cumulus-vx.breakouts must define at least one breakout")
	}

	layout := &portLayout{
		ports:     cfg.Ports,
		breakouts: maps.Clone(cfg.Breakouts),
		starts:    make(map[int]int, len(cfg.Breakouts)),
		lastIndex: cfg.Ports,
	}
	// Match vrnetlab's _compute_renames: append all lanes after the base ports,
	// processing parents numerically, including lanes with no connected link.
	for _, parent := range slices.Sorted(maps.Keys(layout.breakouts)) {
		width := layout.breakouts[parent]
		if parent < 1 || parent > cfg.Ports {
			return nil, fmt.Errorf(
				"breakout port %d is outside the base port range 1..%d",
				parent,
				cfg.Ports,
			)
		}
		switch width {
		case 2, 4, 8:
		default:
			return nil, fmt.Errorf(
				"breakout port %d must have 2, 4, or 8 lanes, got %d",
				parent,
				width,
			)
		}
		layout.starts[parent] = layout.lastIndex + 1
		layout.lastIndex += width
		if layout.lastIndex > maxInterfaceIndex {
			return nil, fmt.Errorf(
				"base ports plus breakout lanes exceed vrnetlab's %d interface indices",
				maxInterfaceIndex,
			)
		}
	}
	return layout, nil
}

// CalculateInterfaceIndex maps native names using the same layout as ports.conf.
func (n *nvidiaCumulusVX) CalculateInterfaceIndex(ifName string) (int, error) {
	groups, err := clabutils.GetRegexpCaptureGroups(InterfaceRegexp, ifName)
	if err != nil {
		return 0, fmt.Errorf("%s: %w", InterfaceHelp, err)
	}
	parent, err := strconv.Atoi(groups["port"])
	if err != nil {
		return 0, fmt.Errorf("invalid port in %q: %w", ifName, err)
	}
	if groups["lane"] == "" {
		if n.portLayout != nil {
			if err := n.portLayout.checkIndex(parent); err != nil {
				return 0, err
			}
			if parent > n.portLayout.ports {
				return 0, fmt.Errorf(
					"%q exceeds the configured %d base ports",
					ifName,
					n.portLayout.ports,
				)
			}
		}
		return parent, nil
	}
	if n.portLayout == nil || n.portLayout.breakouts[parent] == 0 {
		return 0, fmt.Errorf(
			"%q requires a breakout for port %d in extras.cumulus-vx",
			ifName,
			parent,
		)
	}
	lane, err := strconv.Atoi(groups["lane"])
	if err != nil || lane >= n.portLayout.breakouts[parent] {
		return 0, fmt.Errorf("%q has an invalid lane; port %d has lanes 0..%d",
			ifName, parent, n.portLayout.breakouts[parent]-1)
	}
	return n.portLayout.starts[parent] + lane, nil
}

func (p *portLayout) checkIndex(index int) error {
	if index < 1 || index > p.lastIndex {
		return fmt.Errorf(
			"eth%d is outside the configured interface range 1..%d",
			index,
			p.lastIndex,
		)
	}
	if p.breakouts[index] != 0 {
		return fmt.Errorf(
			"swp%d (eth%d) is a breakout parent; use its swp%dsM lanes",
			index,
			index,
			index,
		)
	}
	return nil
}

func (n *nvidiaCumulusVX) CheckInterfaceName() error {
	if err := n.VRNode.CheckInterfaceName(); err != nil {
		return err
	}
	for _, ep := range n.Endpoints {
		index, err := strconv.Atoi(strings.TrimPrefix(ep.GetIfaceName(), "eth"))
		if err != nil {
			return fmt.Errorf("invalid interface %q: %s", ep.GetIfaceName(), InterfaceHelp)
		}
		if n.portLayout != nil {
			if err := n.portLayout.checkIndex(index); err != nil {
				return err
			}
		}
	}
	return nil
}

func (n *nvidiaCumulusVX) writePortsConfig() error {
	if n.portLayout == nil {
		return nil
	}

	var content strings.Builder
	content.WriteString(portsConfigHeader)
	for port := 1; port <= n.portLayout.ports; port++ {
		width := 1
		if lanes := n.portLayout.breakouts[port]; lanes != 0 {
			width = lanes
		}
		fmt.Fprintf(&content, "%d=%dx\n", port, width)
	}
	filename := filepath.Join(n.Cfg.LabDir, configDirName, portsConfigName)
	if err := clabutils.CreateFile(filename, content.String()); err != nil {
		return fmt.Errorf("writing ports.conf: %w", err)
	}
	return nil
}

func (n *nvidiaCumulusVX) ComputeDiff(
	oldCfg, newCfg *clabtypes.NodeConfig,
) *clabtypes.TopologyDiff {
	diff := n.DefaultNode.ComputeDiff(oldCfg, newCfg)
	if oldCfg == nil || newCfg == nil {
		return diff
	}
	a, b := cumulusExtras(oldCfg), cumulusExtras(newCfg)
	if a == nil && b == nil {
		return diff
	}
	if a == nil || b == nil || a.Ports != b.Ports || !maps.Equal(a.Breakouts, b.Breakouts) {
		diff.Fields = append(diff.Fields, portLayoutDiffField)
	}
	return diff
}

func (n *nvidiaCumulusVX) GetReconcilePlan(
	ctx context.Context,
	diff *clabtypes.TopologyDiff,
) (*clabnodes.ReconcileResult, error) {
	// Recreating only the container reuses the guest overlay and its old udev
	// rules. The launcher cannot reliably undo those rules after a layout change.
	if diff != nil && slices.Contains(diff.Fields, portLayoutDiffField) {
		return nil, fmt.Errorf("changing the Cumulus VX port layout requires a fresh guest disk; " +
			"save the guest configuration and use containerlab deploy --reconfigure")
	}
	return n.VRNode.GetReconcilePlan(ctx, diff)
}
