package core

import (
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/charmbracelet/log"

	"gopkg.in/yaml.v2"

	clabtypes "github.com/srl-labs/containerlab/types"
)

type LabState struct {
	Topology *clabtypes.Topology                `yaml:"topology"`
	IPAM     map[string]clabtypes.NodeAddresses `yaml:"ipam,omitempty"`
}

// WriteState saves the topology to the state file.
func (c *CLab) WriteState() error {
	state := &LabState{
		Topology: c.Config.Topology,
	}

	c.writeIPAMState(state)

	data, err := yaml.Marshal(state)
	if err != nil {
		return fmt.Errorf("failed to marshal state: %w", err)
	}

	header := fmt.Sprintf("# generated by containerlab at %s\n", time.Now().Format(time.RFC3339))
	content := append([]byte(header), data...)

	statePath := c.TopoPaths.StateFile()
	temp, err := os.CreateTemp(filepath.Dir(statePath), ".state.clab-*.tmp")
	if err != nil {
		return fmt.Errorf("create state file: %w", err)
	}
	defer os.Remove(temp.Name())
	if err := temp.Chmod(0644); err != nil {
		temp.Close()
		return err
	}
	if _, err := temp.Write(content); err != nil {
		temp.Close()
		return err
	}
	if err := temp.Sync(); err != nil {
		temp.Close()
		return err
	}
	if err := temp.Close(); err != nil {
		return err
	}
	if err := os.Rename(temp.Name(), statePath); err != nil {
		return fmt.Errorf("replace state file %s: %w", statePath, err)
	}

	return nil
}

func (c *CLab) writeIPAMState(state *LabState) {
	state.IPAM = make(map[string]clabtypes.NodeAddresses)
	if c.Config.Mgmt == nil || c.Config.Mgmt.IPAM.Provider == clabtypes.IPAMProviderRuntime {
		return
	}
	previous, err := c.LoadState()
	if err != nil {
		log.Warn("Unable to preserve previous allocation preferences", "error", err)
	}
	for name, node := range c.Nodes {
		cfg := node.Config()
		if !cfg.ManagementIPAMEligible() {
			continue
		}
		addresses := clabtypes.NodeAddresses{}
		if previous != nil {
			addresses = previous.IPAM[name]
		}
		if cfg.MgmtIPv4Address != "" {
			addresses.IPv4 = cfg.MgmtIPv4Address
		}
		if cfg.MgmtIPv6Address != "" {
			addresses.IPv6 = cfg.MgmtIPv6Address
		}
		if c.Config.Mgmt.IPv4Subnet == "" {
			addresses.IPv4 = ""
		}
		if c.Config.Mgmt.IPv6Subnet == "" {
			addresses.IPv6 = ""
		}
		if c.Config.Topology != nil {
			if def := c.Config.Topology.Nodes[name]; def != nil {
				if def.MgmtIPv4 != "" {
					addresses.IPv4 = ""
				}
				if def.MgmtIPv6 != "" {
					addresses.IPv6 = ""
				}
			}
		}
		if addresses.IPv4 != "" || addresses.IPv6 != "" {
			state.IPAM[name] = addresses
		}
	}
}

// LoadState reads the desired topology and optional allocation preferences from the labdir.
func (c *CLab) LoadState() (*LabState, error) {
	if c.TopoPaths == nil {
		return nil, nil
	}
	statePath := c.TopoPaths.StateFile()

	data, err := os.ReadFile(statePath)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("failed to read state file %s: %w", statePath, err)
	}

	state := &LabState{}
	if err := yaml.Unmarshal(data, state); err != nil {
		return nil, fmt.Errorf("failed to unmarshal state: %w", err)
	}

	return state, nil
}
