// Code generated by MockGen. DO NOT EDIT.
// Source: core/exec.go
//
// Generated by this command:
//
//	mockgen -package=mocks -source=core/exec.go -destination=./mocks/exec.go
//

// Package mocks is a generated GoMock package.
package mocks
