comment { Generated by containerlab }

create host-interface v2 name eth1
set interface name host-eth1 eth1
set interface mtu 9216 eth1
set interface state eth1 up

comment { set interface ip address eth1 172.19.1.2/24 }
comment { set interface ip address eth1 fec0::2/64 }

