name: build-clab

"on":
  workflow_call:
    inputs:
      go_ver:
        required: true
        type: string
      runner:
        required: true
        type: string
      arch:
        required: true
        type: string

jobs:
  build-clab:
    runs-on: ${{ inputs.runner }}
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version: ${{ inputs.go_ver }}
          cache: true
          cache-dependency-path: go.sum

      - name: Build containerlab for tests
        if: inputs.arch == 'amd64'
        run: GOOS=linux GOARCH=${{ inputs.arch }} make build-with-podman-debug BINARY=containerlab

      - name: Upload test containerlab binary
        if: inputs.arch == 'amd64'
        uses: actions/upload-artifact@v7
        with:
          name: containerlab-tests
          path: containerlab
          compression-level: 0

      - name: Build portable containerlab
        run: GOOS=linux GOARCH=${{ inputs.arch }} make build-with-podman BINARY=containerlab

      - name: Upload containerlab binary
        uses: actions/upload-artifact@v7
        with:
          name: containerlab${{ inputs.arch == 'arm64' && '-arm64' || '' }}
          path: containerlab
          compression-level: 0
