name: vyosnetworks_vyos-tests

"on":
  workflow_call:
    inputs:
      py_ver:
        required: true
        type: string
      runtime:
        type: string
        default: "docker"

jobs:
  vyosnetworks_vyos-tests:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        test-suite:
          - "01*.robot"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v4
        with:
          name: containerlab

      - name: Move containerlab to usr/bin
        run: sudo mv ./containerlab /usr/bin/containerlab && sudo chown root:root /usr/bin/containerlab && sudo chmod 4755 /usr/bin/containerlab

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          # Install a specific version of uv.
          version: "0.5.28"
          enable-cache: true

      - uses: actions/setup-python@v5
        with:
          # cache: pip
          # cache-dependency-path: "tests/requirements.txt"
          python-version-file: "pyproject.toml"

      - name: Install the project
        run: uv sync --all-extras --dev

      # - name: setup tmate session
      #   uses: mxschmitt/action-tmate@v3

      - name: Activate virtualenv
        run: |
          . .venv/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV

      - name: Sanitize test-suite name
        run: echo "TEST_SUITE=$(echo ${{ matrix.test-suite }} | tr -d '*')" >> $GITHUB_ENV

      # - name: setup tmate session
      #   uses: mxschmitt/action-tmate@v3

      - name: Run tests
        run: |
          bash ./tests/rf-run.sh ${{ inputs.runtime }} ./tests/12-basic-vyos/${{ matrix.test-suite }}

      # upload test reports as a zip file
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: 12-basic-vyos-log-${{ env.TEST_SUITE }}-${{ inputs.runtime }}
          path: ./tests/out/*.html

      # upload coverage report from unit tests, as they are then
      # merged with e2e tests coverage
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-vyosnetworks_vyos-tests-${{ env.TEST_SUITE }}-${{ inputs.runtime }}
          path: /tmp/clab-tests/coverage/*
          retention-days: 7
